title: xss-test-'"onhover="alert(document.domain)"
description: >-
  Duis sed dapibus diam. Proin eu feugiat justo, et dapibus lacus. Ut sed sem
  quis ligula efficitur dignissim. Quisque id euismod lectus. Vestibulum sit
  amet dolor eget augue venenatis luctus id non orci. Nunc lacinia est id lectus
  blandit, in pharetra odio
template:
  repo: xss-test-'"onhover"alert(document.domain)"-template
  name: xss-test-'"onhover"alert(document.domain)"
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
